// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GxNL8DYZus70YabwARkH89QJWorO7VM',
    appId: '1:383482562310:web:7576f2a47df13b4b1b8087',
    messagingSenderId: '383482562310',
    projectId: 'typeracerapp',
    authDomain: 'typeracerapp.firebaseapp.com',
    databaseURL: 'https://typeracerapp-default-rtdb.firebaseio.com',
    storageBucket: 'typeracerapp.firebasestorage.app',
    measurementId: 'G-F6T8YKGYQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDApPlxdVlMrWtv06hN7xWSgslHHk2MQ',
    appId: '1:383482562310:android:2bc681907ecadef91b8087',
    messagingSenderId: '383482562310',
    projectId: 'typeracerapp',
    databaseURL: 'https://typeracerapp-default-rtdb.firebaseio.com',
    storageBucket: 'typeracerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwLL-3BLXa2az_et7oDKPbCRx4yKTmeWo',
    appId: '1:383482562310:ios:9c960eb5346ce92f1b8087',
    messagingSenderId: '383482562310',
    projectId: 'typeracerapp',
    databaseURL: 'https://typeracerapp-default-rtdb.firebaseio.com',
    storageBucket: 'typeracerapp.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwLL-3BLXa2az_et7oDKPbCRx4yKTmeWo',
    appId: '1:383482562310:ios:9c960eb5346ce92f1b8087',
    messagingSenderId: '383482562310',
    projectId: 'typeracerapp',
    databaseURL: 'https://typeracerapp-default-rtdb.firebaseio.com',
    storageBucket: 'typeracerapp.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1GxNL8DYZus70YabwARkH89QJWorO7VM',
    appId: '1:383482562310:web:dfd3a1603c2e74381b8087',
    messagingSenderId: '383482562310',
    projectId: 'typeracerapp',
    authDomain: 'typeracerapp.firebaseapp.com',
    databaseURL: 'https://typeracerapp-default-rtdb.firebaseio.com',
    storageBucket: 'typeracerapp.firebasestorage.app',
    measurementId: 'G-VCN2K10QD1',
  );
}
